apiVersion: v1
kind: Secret
metadata:
  name: saldos-secret
  labels:
    app: saldos
type: Opaque
stringData:
  DATABASE_URL: "mysql://root:PASSWORD@mysql:3306/cuentas"
  API_KEY: "API_KEY_PLACEHOLDER"
